#!/usr/bin/env python3
"""Generate a Verilog define header for cache parameter sweeps."""

from __future__ import annotations

import argparse
from pathlib import Path


ALLOWED_TILE = {4, 8, 16, 32}
ALLOWED_SET = {16, 32, 64, 128, 256}
ALLOWED_WAY = {2, 4, 8}
ALLOWED_MERGE = {1, 2, 4, 8, 16}
ALLOWED_FIFO = {8, 16, 32, 64, 128}
ALLOWED_LEAD = {0, 8, 16, 32, 64, 128, 256, 512}
ALLOWED_RD_BURST = {8, 16, 32, 64}
ALLOWED_RD_OUTSTANDING_BURSTS = {2, 4, 8}
ALLOWED_RD_OUTSTANDING_BEATS = {16, 32, 64, 128}
ALLOWED_RD_FIFO_WORDS = {64, 128, 256}
ALLOWED_WR_BURST = {8, 16, 32, 64}
ALLOWED_WR_FIFO_PIXELS = {128, 256, 512, 1024}


def require_allowed(name: str, value: int, allowed: set[int]) -> None:
    if value not in allowed:
        allowed_str = ", ".join(str(v) for v in sorted(allowed))
        raise SystemExit(f"{name}={value} is not allowed; choose one of: {allowed_str}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="sim_out/cache_param_override.svh")
    parser.add_argument("--tile-w", type=int, default=8)
    parser.add_argument("--tile-h", type=int, default=8)
    parser.add_argument("--set-num", type=int, default=64)
    parser.add_argument("--way-num", type=int, default=4)
    parser.add_argument("--merge-max-x", type=int, default=8)
    parser.add_argument("--enable-merge-min", type=int, choices=[0, 1], default=0)
    parser.add_argument("--merge-min-x", type=int, default=1)
    parser.add_argument("--fifo-age-limit", type=int, default=0)
    parser.add_argument("--enable-prefetch-throttle", type=int, choices=[0, 1], default=0)
    parser.add_argument("--prefetch-throttle-cycles", type=int, default=0)
    parser.add_argument("--enable-row-bucket-merge", type=int, choices=[0, 1], default=0)
    parser.add_argument("--row-bucket-min-x", type=int, default=3)
    parser.add_argument("--fifo-depth", type=int, default=32)
    parser.add_argument("--lead-pixels", type=int, default=64)
    parser.add_argument("--legacy-tile-w", type=int, default=64)
    parser.add_argument("--legacy-tile-h", type=int, default=8)
    parser.add_argument("--legacy-tile-num", type=int, default=24)
    parser.add_argument("--rd-burst-max-len", type=int, default=16)
    parser.add_argument("--rd-max-outstanding-bursts", type=int, default=4)
    parser.add_argument("--rd-max-outstanding-beats", type=int, default=16)
    parser.add_argument("--rd-fifo-depth-words", type=int, default=64)
    parser.add_argument("--wr-burst-max-len", type=int, default=16)
    parser.add_argument("--wr-fifo-depth-pixels", type=int, default=256)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    require_allowed("BASE_TILE_W", args.tile_w, ALLOWED_TILE)
    require_allowed("BASE_TILE_H", args.tile_h, ALLOWED_TILE)
    require_allowed("SET_NUM", args.set_num, ALLOWED_SET)
    require_allowed("WAY_NUM", args.way_num, ALLOWED_WAY)
    require_allowed("MERGE_MAX_X", args.merge_max_x, ALLOWED_MERGE)
    if args.merge_min_x < 1 or args.merge_min_x > args.merge_max_x:
        raise SystemExit("MERGE_MIN_X must be in [1, MERGE_MAX_X]")
    if args.fifo_age_limit < 0:
        raise SystemExit("FIFO_AGE_LIMIT must be >= 0")
    if args.prefetch_throttle_cycles < 0:
        raise SystemExit("PREFETCH_THROTTLE_CYCLES must be >= 0")
    if args.enable_row_bucket_merge and (args.row_bucket_min_x < 2 or args.row_bucket_min_x > args.merge_max_x):
        raise SystemExit("ROW_BUCKET_MIN_X must be in [2, MERGE_MAX_X]")
    require_allowed("ANALYTIC_FIFO_DEPTH", args.fifo_depth, ALLOWED_FIFO)
    require_allowed("ANALYTIC_LEAD_PIXELS", args.lead_pixels, ALLOWED_LEAD)
    require_allowed("IMAGE_GEO_RD_BURST_MAX_LEN", args.rd_burst_max_len, ALLOWED_RD_BURST)
    require_allowed("IMAGE_GEO_RD_MAX_OUTSTANDING_BURSTS", args.rd_max_outstanding_bursts, ALLOWED_RD_OUTSTANDING_BURSTS)
    require_allowed("IMAGE_GEO_RD_MAX_OUTSTANDING_BEATS", args.rd_max_outstanding_beats, ALLOWED_RD_OUTSTANDING_BEATS)
    require_allowed("IMAGE_GEO_RD_FIFO_DEPTH_WORDS", args.rd_fifo_depth_words, ALLOWED_RD_FIFO_WORDS)
    require_allowed("IMAGE_GEO_WR_BURST_MAX_LEN", args.wr_burst_max_len, ALLOWED_WR_BURST)
    require_allowed("IMAGE_GEO_WR_FIFO_DEPTH_PIXELS", args.wr_fifo_depth_pixels, ALLOWED_WR_FIFO_PIXELS)
    if args.fifo_depth < args.merge_max_x:
        raise SystemExit("ANALYTIC_FIFO_DEPTH must be >= MERGE_MAX_X")
    if args.merge_max_x * args.tile_w > 128:
        raise SystemExit("MERGE_MAX_X * BASE_TILE_W must stay <= 128 bytes for the safe sweep range")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Auto-generated by scripts/gen_param_header.py. Do not edit by hand.",
        f"`define SRC_TILE_CACHE_BASE_TILE_W {args.tile_w}",
        f"`define SRC_TILE_CACHE_BASE_TILE_H {args.tile_h}",
        f"`define SRC_TILE_CACHE_SECTOR_SET_NUM {args.set_num}",
        f"`define SRC_TILE_CACHE_SECTOR_WAY_NUM {args.way_num}",
        f"`define SRC_TILE_CACHE_MERGE_MAX_X {args.merge_max_x}",
        f"`define SRC_TILE_CACHE_ENABLE_MERGE_MIN {args.enable_merge_min}",
        f"`define SRC_TILE_CACHE_MERGE_MIN_X {args.merge_min_x}",
        f"`define SRC_TILE_CACHE_FIFO_AGE_LIMIT {args.fifo_age_limit}",
        f"`define SRC_TILE_CACHE_ENABLE_PREFETCH_THROTTLE {args.enable_prefetch_throttle}",
        f"`define SRC_TILE_CACHE_PREFETCH_THROTTLE_CYCLES {args.prefetch_throttle_cycles}",
        f"`define SRC_TILE_CACHE_ENABLE_ROW_BUCKET_MERGE {args.enable_row_bucket_merge}",
        f"`define SRC_TILE_CACHE_ROW_BUCKET_MIN_X {args.row_bucket_min_x}",
        f"`define SRC_TILE_CACHE_ANALYTIC_FIFO_DEPTH {args.fifo_depth}",
        f"`define SRC_TILE_CACHE_ANALYTIC_LEAD_PIXELS {args.lead_pixels}",
        f"`define IMAGE_GEO_SRC_TILE_W {args.legacy_tile_w}",
        f"`define IMAGE_GEO_SRC_TILE_H {args.legacy_tile_h}",
        f"`define IMAGE_GEO_SRC_TILE_NUM {args.legacy_tile_num}",
        f"`define IMAGE_GEO_RD_BURST_MAX_LEN {args.rd_burst_max_len}",
        f"`define IMAGE_GEO_RD_MAX_OUTSTANDING_BURSTS {args.rd_max_outstanding_bursts}",
        f"`define IMAGE_GEO_RD_MAX_OUTSTANDING_BEATS {args.rd_max_outstanding_beats}",
        f"`define IMAGE_GEO_RD_FIFO_DEPTH_WORDS {args.rd_fifo_depth_words}",
        f"`define IMAGE_GEO_WR_BURST_MAX_LEN {args.wr_burst_max_len}",
        f"`define IMAGE_GEO_WR_FIFO_DEPTH_PIXELS {args.wr_fifo_depth_pixels}",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
