set repo_root [file normalize [file join [file dirname [info script]] ".."]]
set reports_dir [file join $repo_root "reports"]
file mkdir $reports_dir

set part_name "xc7z020clg400-1"
if {[info exists ::env(IMAGE_GEO_VIVADO_PART)]} {
    set part_name $::env(IMAGE_GEO_VIVADO_PART)
}
set report_mode "synth"
if {[info exists ::env(IMAGE_GEO_REPORT_MODE)]} {
    set report_mode $::env(IMAGE_GEO_REPORT_MODE)
}
if {[llength $argv] >= 1} {
    set report_mode [lindex $argv 0]
}
set small_config 0
set small_timing_safe 0
if {[llength $argv] >= 2} {
    if {[lindex $argv 1] eq "small"} {
        set small_config 1
    } elseif {[lindex $argv 1] eq "small_timing_safe"} {
        set small_timing_safe 1
    }
}

set verilog_defines [list]
if {$small_config || $small_timing_safe} {
    set define_file [file join $reports_dir "vivado_report_defines.sv"]
    set fd [open $define_file "w"]
    if {$small_timing_safe} {
        puts $fd "// Generated by tools/image_geo_reports.tcl small_timing_safe mode"
    } else {
        puts $fd "// Generated by tools/image_geo_reports.tcl small mode"
    }
    puts $fd "`define SRC_TILE_CACHE_BASE_TILE_W 8"
    puts $fd "`define SRC_TILE_CACHE_BASE_TILE_H 8"
    if {$small_timing_safe} {
        puts $fd "`define SRC_TILE_CACHE_SECTOR_SET_NUM 32"
    } else {
        puts $fd "`define SRC_TILE_CACHE_SECTOR_SET_NUM 16"
    }
    puts $fd "`define SRC_TILE_CACHE_SECTOR_WAY_NUM 2"
    if {$small_timing_safe} {
        puts $fd "`define SRC_TILE_CACHE_MERGE_MAX_X 4"
        puts $fd "`define SRC_TILE_CACHE_ANALYTIC_FIFO_DEPTH 16"
    } else {
        puts $fd "`define SRC_TILE_CACHE_MERGE_MAX_X 2"
        puts $fd "`define SRC_TILE_CACHE_ANALYTIC_FIFO_DEPTH 8"
    }
    puts $fd "`define SRC_TILE_CACHE_ANALYTIC_LEAD_PIXELS 16"
    puts $fd "`define IMAGE_GEO_RD_BURST_MAX_LEN 8"
    puts $fd "`define IMAGE_GEO_RD_MAX_OUTSTANDING_BURSTS 2"
    puts $fd "`define IMAGE_GEO_RD_MAX_OUTSTANDING_BEATS 8"
    puts $fd "`define IMAGE_GEO_RD_FIFO_DEPTH_WORDS 32"
    puts $fd "`define IMAGE_GEO_WR_BURST_MAX_LEN 8"
    puts $fd "`define IMAGE_GEO_WR_FIFO_DEPTH_PIXELS 64"
    close $fd
}

set sources [list \
    "axi/rtl/taxi_axi_if.sv" \
    "rtl/axi/ddr_axi_pkg.sv" \
    "rtl/axi/reset_sync.sv" \
    "rtl/axi/task_cdc.sv" \
    "rtl/axi/task_cdc_2d.sv" \
    "rtl/axi/result_cdc.sv" \
    "rtl/axi/frame_config_cdc.sv" \
    "rtl/axi/cache_stats_cdc.sv" \
    "rtl/axi/axi_burst_reader.sv" \
    "rtl/axi/axi_burst_writer.sv" \
    "rtl/buffer/async_word_fifo.sv" \
    "rtl/core/pixel_packer.sv" \
    "rtl/core/pixel_unpacker.sv" \
    "rtl/core/rotate_geom_init_unit.sv" \
    "rtl/axi/ddr_read_engine.sv" \
    "rtl/axi/ddr_write_engine.sv" \
    "rtl/buffer/src_tile_cache.sv" \
    "rtl/buffer/row_out_buffer.sv" \
    "rtl/core/row_advance_unit.sv" \
    "rtl/core/rotate_core_bilinear.sv" \
    "rtl/ctrl/scaler_ctrl.sv" \
    "rtl/top/image_geo_top.sv" \
]

set read_sources [list]
if {[info exists ::env(XILINX_VIVADO)]} {
    set xpm_fifo [file join $::env(XILINX_VIVADO) "data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv"]
    set xpm_cdc [file join $::env(XILINX_VIVADO) "data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv"]
    if {[file exists $xpm_cdc]} {
        lappend read_sources $xpm_cdc
    }
    if {[file exists $xpm_fifo]} {
        lappend read_sources $xpm_fifo
    }
}
if {$small_config} {
    lappend read_sources [file join $reports_dir "vivado_report_defines.sv"]
}
foreach src $sources {
    lappend read_sources [file join $repo_root $src]
}
read_verilog -sv $read_sources

read_xdc [file join $repo_root "constraints/cdc_image_geo_top.xdc"]
if {$report_mode eq "rtl"} {
    synth_design -rtl -top image_geo_top -part $part_name -mode out_of_context
    set fd [open [file join $reports_dir "report_elaboration_status.rpt"] "w"]
    puts $fd "image_geo_top RTL elaboration completed."
    puts $fd "Mode: rtl"
    puts $fd "Small config: $small_config"
    puts $fd "Small timing safe: $small_timing_safe"
    puts $fd "Note: report_cdc/report_timing_summary require a synthesized design and are not emitted in rtl mode."
    close $fd
    exit 0
} else {
    synth_design -top image_geo_top -part $part_name -mode out_of_context
}

report_cdc -file [file join $reports_dir "report_cdc.rpt"]
report_cdc -details -file [file join $reports_dir "report_cdc_details.rpt"]
report_clock_interaction -file [file join $reports_dir "report_clock_interaction.rpt"]
report_exceptions -file [file join $reports_dir "report_exceptions.rpt"]
report_timing_summary -file [file join $reports_dir "report_timing_summary.rpt"]
