[CmdletBinding()]
param(
    [int]$TimeoutSec = 300,
    [ValidateSet("synth", "rtl")]
    [string]$Mode = "synth",
    [switch]$SmallConfig,
    [switch]$SmallTimingSafe
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $repoRoot "reports"
New-Item -ItemType Directory -Path $outDir -Force | Out-Null
$log = Join-Path $outDir "vivado_reports.log"
$tcl = Join-Path $PSScriptRoot "image_geo_reports.tcl"
$defines = Join-Path $outDir "vivado_report_defines.sv"
if ($SmallConfig -and $SmallTimingSafe) {
    throw "-SmallConfig and -SmallTimingSafe are mutually exclusive"
}

if ($SmallTimingSafe) {
    Set-Content -Path $defines -Value @(
        "// Generated by tools/run-vivado-reports.ps1 -SmallTimingSafe",
        "``define SRC_TILE_CACHE_BASE_TILE_W 8",
        "``define SRC_TILE_CACHE_BASE_TILE_H 8",
        "``define SRC_TILE_CACHE_SECTOR_SET_NUM 32",
        "``define SRC_TILE_CACHE_SECTOR_WAY_NUM 2",
        "``define SRC_TILE_CACHE_MERGE_MAX_X 4",
        "``define SRC_TILE_CACHE_ANALYTIC_FIFO_DEPTH 16",
        "``define SRC_TILE_CACHE_ANALYTIC_LEAD_PIXELS 16",
        "``define IMAGE_GEO_RD_BURST_MAX_LEN 8",
        "``define IMAGE_GEO_RD_MAX_OUTSTANDING_BURSTS 2",
        "``define IMAGE_GEO_RD_MAX_OUTSTANDING_BEATS 8",
        "``define IMAGE_GEO_RD_FIFO_DEPTH_WORDS 32",
        "``define IMAGE_GEO_WR_BURST_MAX_LEN 8",
        "``define IMAGE_GEO_WR_FIFO_DEPTH_PIXELS 64"
    )
} elseif ($SmallConfig) {
    Set-Content -Path $defines -Value @(
        "// Generated by tools/run-vivado-reports.ps1 -SmallConfig",
        "``define SRC_TILE_CACHE_BASE_TILE_W 8",
        "``define SRC_TILE_CACHE_BASE_TILE_H 8",
        "``define SRC_TILE_CACHE_SECTOR_SET_NUM 16",
        "``define SRC_TILE_CACHE_SECTOR_WAY_NUM 2",
        "``define SRC_TILE_CACHE_MERGE_MAX_X 2",
        "``define SRC_TILE_CACHE_ANALYTIC_FIFO_DEPTH 8",
        "``define SRC_TILE_CACHE_ANALYTIC_LEAD_PIXELS 16",
        "``define IMAGE_GEO_RD_BURST_MAX_LEN 8",
        "``define IMAGE_GEO_RD_MAX_OUTSTANDING_BURSTS 2",
        "``define IMAGE_GEO_RD_MAX_OUTSTANDING_BEATS 8",
        "``define IMAGE_GEO_RD_FIFO_DEPTH_WORDS 32",
        "``define IMAGE_GEO_WR_BURST_MAX_LEN 8",
        "``define IMAGE_GEO_WR_FIFO_DEPTH_PIXELS 64"
    )
} elseif (Test-Path $defines) {
    Remove-Item -LiteralPath $defines -Force
}

function Stop-VivadoProcesses {
    $procs = Get-Process -ErrorAction SilentlyContinue | Where-Object {
        $_.ProcessName -like "vivado*"
    }
    foreach ($proc in $procs) {
        Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
    }
}

$vivado = (Get-Command vivado -ErrorAction Stop).Source
$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName = $vivado
$smallArg = if ($SmallTimingSafe) { " small_timing_safe" } elseif ($SmallConfig) { " small" } else { "" }
$psi.Arguments = "-mode batch -notrace -nojournal -log `"$log`" -source `"$tcl`" -tclargs $Mode$smallArg"
$psi.WorkingDirectory = $repoRoot
$psi.UseShellExecute = $false
$psi.CreateNoWindow = $true
$proc = New-Object System.Diagnostics.Process
$proc.StartInfo = $psi
[void]$proc.Start()

$done = $false
for ($i = 0; $i -lt $TimeoutSec; $i++) {
    $proc.Refresh()
    if ($proc.HasExited) {
        $done = $true
        break
    }
    Start-Sleep -Seconds 1
}

if (-not $done) {
    Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue
    Stop-VivadoProcesses
    throw "vivado reports timed out after ${TimeoutSec}s. See $log"
}

if ($proc.ExitCode -ne 0) {
    throw "vivado reports failed with exit code $($proc.ExitCode). See $log"
}

Write-Host "Vivado reports generated in $outDir"
